name: CI
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: ["8.0.2", "8.2.2", "8.4.2", "8.6.5", "8.8.1", "8.10.7", "9.2.7", "9.6.3", "9.8.1" ]
    env:
      CONFIG: "--enable-tests"
    steps:
      - uses: actions/checkout@v2
      - name: "Setup haskell"
        uses: haskell/actions/setup@v2
        id: setup-haskell
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: 3.10.1.0
      - run: cabal update
      - run: cabal freeze $CONFIG
      - uses: actions/cache@v2
        with:
          path: ${{ steps.setup-haskell.outputs.cabal-store }}
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
            ${{ runner.os }}-${{ matrix.ghc }}-
      - run: cabal build $CONFIG
      - run: cabal test $CONFIG
      - run: cabal haddock $CONFIG
      - run: cabal sdist
